Mutation:
  type: object
  config:
    fields:
      editGuest:
        type: EditGuestPayload!
        args:
          input: EditGuestInput!
        resolve: '@=mutation("App\\Mutations\\GuestMutation::editGuest", args)'
      selectDrinks:
        type: SelectDrinksPayload!
        args:
          input: SelectDrinksInput!
        resolve: '@=mutation("App\\Mutations\\DrinkMutation::select", args)'

EditGuestPayload:
  type: object
  config:
    fields:
      guest: Guest

EditGuestInput:
  type: input-object
  config:
    fields:
      id: ID!
      willAttend: Boolean

SelectDrinksPayload:
  type: object
  config:
    fields:
      success: Boolean

SelectDrinksInput:
  type: input-object
  config:
    fields:
      guestId: ID!
      drinkIds: '[ID!]'